GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTkzMzUzMTMyfQ.8Mc8gLpMrDv2ZfrzXSyW2RvKZR-7Sq2oRmwyj9yHH2g

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}