GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTkzMzU3NTgzLCJleHAiOjE1OTMzNTc1OTh9.veAX8cOP9Ng0ULTJZSbTOGPHOKA-8ohs4GCpVMSAMlw

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTkzMzU3NTQ0fQ.uTa4IFAg0RD7QErwwMsyHWx40rpvYeS6slNVj36Mtlw"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTkzMzU3NTQ0fQ.uTa4IFAg0RD7QErwwMsyHWx40rpvYeS6slNVj36Mtlw"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}